name: CICD

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.TF_USER_AWS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_USER_AWS_SECRET }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Create SSH Key Files
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/my-key-pair.pem
          echo "${{ secrets.EC2_SSH_PUBLIC_KEY }}" > ~/.ssh/my-key-pair.pub
          chmod 600 ~/.ssh/my-key-pair.pem

      - name: Terraform Init
        run: terraform init
      
      # - name: Download terraform.tfstate from S3
      #   run: |
      #     aws s3 cp s3://kha-app-s3/state/terraform.tfstate .  

      - name: Terraform Apply
        run: terraform apply -auto-approve
  # build:
  #   needs: terraform
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Source
  #       uses: actions/checkout@v3
  #     - name: Login to Docker Hub
  #       run: docker login -u 
  #     - name: Build Docker Image
  #       run: docker build -t khanguyentuan/reactjs-app .
  #     - name: Publish image to docker hub
  #       run: docker push khanguyentuan/reactjs-app:latest   

  # deploy: 
  #   needs: build
  #   runs-on: ubuntu-lastest   
  #   steps:
  #     - name: Get EC2 IP
  #       id: ec2_ip
  #       run: echo "EC2_IP=$(terraform output -raw instance_ip)" >> $GITHUB_ENV

  #     - name: Pull image from Docker Hub
  #       run: |
  #         ssh -o StrictHostKeyChecking=no -i path/to/my-key-pair.pem ec2-user@$EC2_IP "docker pull khanguyentuan/reactjs-app:latest"

  #     - name: Delete Old Container
  #       run: |
  #         ssh -o StrictHostKeyChecking=no -i path/to/my-key-pair.pem ec2-user@$EC2_IP "docker rm -f reactContainer || true"

  #     - name: Run Docker Container
  #       run: |
  #         ssh -o StrictHostKeyChecking=no -i path/to/my-key-pair.pem ec2-user@$EC2_IP "docker run -d -p 3000:80 --name reactContainer khanguyentuan/reactjs-app:latest"